version: "3.7"

services:
      nginx:
          container_name: nginx
          networks:
            - mamak
          build:  ./req/nginx/
          depends_on:
            - wordpress
          ports:
            - "443:443"
          volumes:
            - wp_files:/var/www/html

      mariadb:
          container_name: mariadb
          networks:
            - mamak
          build:  ./req/mariadb/
          ports:
            - "3306:3306"
          volumes:
            - wp_database:/var/lib/mysql

      wordpress:
          container_name: wordpress
          networks:
            - mamak
          build:  ./req/wordpress+php-fpm/
          ports:
            - "9000:9000"
          depends_on:
            - mariadb
          volumes:
            - wp_files:/var/www/html

networks:
      mamak: {}

volumes:
      wp_database:
        driver_opts:
          type: none
          device: /home/yabtaour/Desktop/volumes/wp_database
          o: bind
      wp_files:
        driver_opts:
          type: none
          device: /home/yabtaour/Desktop/volumes/wp_files
          o: bind       