version: "3.7"

services:
      nginx:
          container_name: nginx
          networks:
            - intra
          build:  ./requirements/nginx/
          depends_on:
            - wordpress
            - adminer
          ports:
            - "443:443"
          volumes:
            - wp_files:/var/www/html
      
      mariadb:
          container_name: mariadb
          networks:
            - intra
          build:  ./requirements/mariadb/
          expose:
            - "3306"
          volumes:
            - wp_database:/var/lib/mysql

      wordpress:
          container_name: wordpress
          networks:
            - intra
          build:  ./requirements/wordpress+php-fpm/
          env_file:
            - ../.env
          expose:
            - "9000"
          depends_on:
            - mariadb
          volumes:
            - wp_files:/var/www/html
      
      static_page:
          container_name: static_page
          build: ./requirements/bonus/static_page/
          ports:
            - "8080:8080"

      adminer:
          container_name: adminer
          networks:
            - intra
          build: ./requirements/bonus/adminer/
          ports:
            - "8000:443"

      redis:
          container_name: redis
          networks:
            - intra
          build: ./requirements/bonus/redis/
          expose:
            - "6379"
      ftp:
          container_name: ftp
          networks:
            - intra
          build: ./requirements/bonus/ftp/
          env_file:
            - ../.env 
          ports:
            - "21:21"
            - "40000-40005:40000-40005"
          volumes:
            - wp_files:/home/ftpuser/ftp

      cadvisor:
          container_name: cadvisor
          networks:
            - intra
          build: ./requirements/bonus/cadvisor
          ports:
            - "8888:8888"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/machine-id:/etc/machine-id:ro
            - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
networks:
      intra: {}

volumes:
      wp_database:
        driver_opts:
          type: local
          device: /home/yabtaour/data/database/
          o: bind
      wp_files:
        driver_opts:
          type: local
          device: /home/yabtaour/data/wp_files/
          o: bind
