version: "3.7"

services:
      nginx:
          container_name: nginx
          networks:
            - mamak
          build:  ./req/nginx/
          depends_on:
            - wordpress
            - adminer
          ports:
            - "443:443"
          volumes:
            - wp_files:/var/www/html
      
      mariadb:
          container_name: mariadb
          networks:
            - mamak
          build:  ./req/mariadb/
          ports:
            - "3306"
          volumes:
            - wp_database:/var/lib/mysql

      wordpress:
          container_name: wordpress
          networks:
            - mamak
          build:  ./req/wordpress+php-fpm/
          ports:
            - "9000"
          depends_on:
            - mariadb
          volumes:
            - wp_files:/var/www/html
      
      static_page:
          container_name: static_page
          build: ./req/static_page/
          ports:
            - "8080:8080"

      adminer:
          container_name: adminer
          networks:
            - mamak
          build: ./req/adminer/
          ports:
            - "8000:443"

networks:
      mamak: {}

volumes:
      wp_database:
        driver_opts:
          type: local
          device: /home/yabtaour/data/wp_database/
          o: bind
      wp_files:
        driver_opts:
          type: local
          device: /home/yabtaour/data/wp_files/
          o: bind
