version: "3.7"

services:
      nginx:
          networks:
            - mamak
          build:  ./req/nginx/
          ports:
            - "443:443"

      wordpress:
          networks:
            - mamak
          build:  ./req/wordpress+php-fpm/
          ports:
            - "9000:9000"

      mariadb:
          networks:
            - mamak
          build:  ./req/mariadb/
          ports:
            - "3306:3306"
networks:
      mamak: {}